name: Kemono Patreon Tracker

on:
  schedule:
    - cron: '0 * * * *'  # Every hour
  workflow_dispatch:     # Manual trigger

jobs:
  check_updates:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Get full history

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run Kemono Tracker script
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: python kemono_tracker.py

      - name: Configure Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Commit & Force Push (Safe since you're the only user)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Or a PAT if needed
        run: |
          git add last_seen.json
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update last_seen.json [skip ci]"
            git pull --rebase origin main  # Try normal pull first
            git push origin main || git push --force-with-lease origin main
          fi
