name: Kemono Patreon Tracker

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  check_updates:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Explicitly grant write permission

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # Critical addition to avoid reference issues
          ref: ${{ github.ref }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run Kemono Tracker script
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: python kemono_tracker.py

      - name: Configure Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          # Ensure the correct branch is tracked
          git branch --set-upstream-to=origin/main main

      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Verify remote connection
          git remote -v
          
          # Pull with rebase to ensure we're up-to-date
          git pull --rebase origin main
          
          # Stage and commit changes
          git add last_seen.json
          if ! git diff --cached --quiet; then
            git commit -m "Update last_seen.json [skip ci]"
            # Push with lease as final safety check
            git push --force-with-lease origin main
          else
            echo "No changes to commit"
          fi
