name: Kemono Patreon Tracker

on:
  schedule:
    - cron: '0 * * * *'  # runs every hour
  workflow_dispatch:    # allows manual trigger

jobs:
  check_updates:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository with full git history
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # important for full history & git pull to work

      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run kemono_tracker.py script
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: python kemono_tracker.py

      - name: Configure git user
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Pull latest changes from remote main branch with rebase
        run: git pull origin main --rebase

      - name: Commit and push updates if any
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add last_seen.json
          # Check if there are changes to commit
          if git diff --cached --quiet; then
            echo "No changes detected, skipping commit."
          else
            git commit -m "Update last_seen.json [skip ci]"
            git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git HEAD:main
          fi
