name: Kemono Patreon Tracker

on:
  schedule:
    - cron: '0 * * * *'  # Runs hourly
  workflow_dispatch:     # Manual trigger

jobs:
  check_updates:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout with NO history
      - name: Checkout fresh
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Gets complete fresh state

      # 2. Setup Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # 3. Run your tracker
      - name: Run Kemono Tracker
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: python kemono_tracker.py

      # 4. COMMIT AND ABSOLUTELY FORCE PUSH
      - name: Force Update last_seen.json
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          
          git add last_seen.json
          git commit -m "Update last_seen.json [skip ci]" || exit 0
          git push origin HEAD:main --force
