name: Kemono Patreon Tracker

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  check_updates:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests pygithub

      - name: Run Kemono Tracker script
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: python kemono_tracker.py

      - name: Update file via GitHub API
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python - <<EOF
          from github import Github
          import json
          import os

          # Initialize GitHub client
          g = Github(os.environ['GITHUB_TOKEN'])
          repo = g.get_repo("bhatmudit/kemono-tracker")

          # Get current file content
          try:
              file = repo.get_contents("last_seen.json")
              current_content = file.decoded_content.decode()
              sha = file.sha
          except:
              current_content = "{}"
              sha = None

          # Read updated content
          with open("last_seen.json", "r") as f:
              new_content = f.read()

          # Update if changed
          if current_content != new_content:
              repo.update_file(
                  path="last_seen.json",
                  message="Update last_seen.json [skip ci]",
                  content=new_content,
                  sha=sha
              )
              print("File updated successfully")
          else:
              print("No changes detected")
          EOF
