name: Kemono Patreon Tracker

on:
  schedule:
    - cron: '0 * * * *'  # every hour
  workflow_dispatch:      # manual trigger

jobs:
  check_updates:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run Kemono Tracker
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: python kemono_tracker.py

      - name: Commit updated last_seen.json
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add last_seen.json
          git diff --cached --quiet || (
            git commit -m "Update last_seen.json [skip ci]"
            git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
            git pull --rebase origin ${{ github.ref_name }}
            git push origin HEAD:${{ github.ref_name }}
          )
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
