name: Kemono Patreon Tracker

on:
  schedule:
    - cron: '0 * * * *'  # Runs hourly
  workflow_dispatch:     # Manual trigger

jobs:
  check_updates:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # Ensure write access

    steps:
      # Step 1: Checkout with NO history
      - name: Checkout fresh copy
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Important: gets fresh state

      # Step 2: Setup Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Step 3: Run your tracker
      - name: Run Kemono Tracker
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: python kemono_tracker.py

      # Step 4: Commit and FORCE push (safe for your use case)
      - name: Update last_seen.json
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          
          git add last_seen.json
          
          # Only commit if there are changes
          if ! git diff --cached --quiet; then
            git commit -m "Update last_seen.json [skip ci]"
            # Force push is SAFE because:
            # 1. It's your private repo
            # 2. The JSON is only for tracking state
            # 3. You're the only user
            git push origin HEAD:main --force
          fi
